name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - redmine-repository: 'redmine/redmine'
            redmine-version: 'master'
            ruby-version: '3.4'

    steps:
      - uses: hidakatsuya/action-setup-redmine@v1
        with:
          repository: ${{ matrix.redmine-repository }}
          version: ${{ matrix.redmine-version }}
          ruby-version: ${{ matrix.ruby-version }}
          database: 'postgres:14'

      - uses: actions/checkout@v4
        with:
          path: plugins/redmine_custom_dashboards

      - name: Run plugin migrations
        run: bin/rails redmine:plugins:migrate RAILS_ENV=test

      - run: bin/rails redmine:plugins:test NAME=redmine_custom_dashboards